services:
  php-apache-oci:
    image: php-oci-c12:php8.4
    hostname: php-oci8
    build:
      context: .
      dockerfile: Dockerfile12p8
    container_name: php-apache-oci
    ports:
      - "2222:80"
    volumes:
      # Mounts the local ./html directory to the container's web root.
      - ./html:/var/www/html
